name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run test
        run: go test -v ./...
