name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run test
        run: go test -v ./...
